### ISSUE TITLE
How can we restrict the users to view only specific applications and their related data

### ISSUE THREAD

**Issue by chinmayshrikhande** [konveyor/konveyor.github.io#12]
Hi,

Currently, I have set up the konveyor tackle locally using Kubernetes by following this guide: https://konveyor.github.io/tackle/installation/

I have created multiple users in keycloak and have assigned them the role of tackle-architect and I am also able to log in using these different users in Tackle.

The problem that I am facing right now is that any application that is created by UserA is also visible to UserB and vice-versa.
Is there a way I can restrict the users to view only specific applications and their related data?

Can you please share your thoughts on this, will be really helpful.
Kindly let me know if this is not the right forum and if I have to ask this question somewhere else.

Thanks!

**Comment by jwmatthews** [comment]
Closing this issue so we may use this open RFE for further discussions related to it:
https://github.com/konveyor/enhancements/issues/110
